services:
  #################################
  # Data Generation Services      #
  #################################

  # financial-generator: Continuously generates and sends mock financial data.
  financial-generator:
    build:
      context: ../data-generators/financial-generator
    ports:
      - "5001:5000"
    container_name: financial-generator
    restart: always
    depends_on:
      fastapi-ingestor:
        condition: service_healthy
    networks:
      - data_platform_network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '128m'

  # insurance-generator: Continuously generates and sends mock insurance data.
  insurance-generator:
    build:
      context: ../data-generators/insurance-generator
    ports:
      - "5002:5000"
    container_name: insurance-generator
    restart: always
    depends_on:
      fastapi-ingestor:
        condition: service_healthy
    networks:
      - data_platform_network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '128m'

  # sports-generator: Continuously generates and sends mock sports data.
  sports-generator:
    build:
      context: ../data-generators/sports-generator
    ports:
      - "5003:5000"
    container_name: sports-generator
    restart: always
    depends_on:
      fastapi-ingestor:
        condition: service_healthy
    networks:
      - data_platform_network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '128m'