# This is the main entrypoint for Docker Compose.
# It uses the 'include' directive to load all the modularized service definitions.
# This allows for a clean separation of concerns and makes the platform easier to manage.
#
# To run the full stack, simply run 'docker compose up'.
# To run a subset of services, you can specify the files directly, e.g.:
#   docker compose -f docker-compose.base.yml -f docker-compose.core.yml up

include:
  - docker-compose.base.yml
  - docker-compose.core.yml
  - docker-compose.generators.yml
  - docker-compose.ingestion.yml
  - docker-compose.processing.yml
  - docker-compose.orchestration.yml
  - docker-compose.dbt.yml
  - docker-compose.governance.yml
  - docker-compose.bi.yml
  - docker-compose.observability.yml
  - docker-compose.emulation.yml
