global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'music-recommendation-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['music-recommendation-service:80']
